name: Updater

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    steps:
       - name: Checkout repository
         uses: actions/checkout@v2
         with:
          ref: test-branch
       - name: Install dependencies
         run: npm install
       - name: Get new data and update stats
         run: npm start
         run: date > datelog.txt
         run: git add datelog.txt
         run: npm run commit
