name: Updater

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login

    steps:
       - name: Checkout repository
         uses: actions/checkout@v2
         with:
          ref: test-branch
       - name: Install dependencies
         run: npm install
       - name: Get new data and update stats
         run: npm start
       - run: date > datelog.txt && git add datelog.txt
       - name: push changes to remote
         run: |
          git add data results
          git \
          -c user.name="GitHub Actions" \
          -c user.email="actions@github.com" \
          --author "${{ github.actor }}@users.noreply.github.com" \
          commit -m "added data for `date +%F`"
          git push
