name: Updater
on:
  schedule:
    - cron: 30 21 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2
       - name: Install dependencies
         run: npm install
       - name: Get new data and update stats
         run: npm start
       - name: push changes to remote
         run: |
          git add data results
          git \
          -c user.name="GitHub Actions" \
          -c user.email="actions@github.com" \
          commit -m "added data for `date +%F`" \
          --author "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git push
